version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - toshimaru
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: font-awesome-sass
    versions:
    - "< 6"
    - ">= 5.0.a"
