language: ruby
cache: bundler
dist: focal
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
rvm:
  - 2.6.5
before_install:
  - gem install bundler
script:
  - bundle exec rails db:migrate
  - bundle exec rails db:populate
  - bundle exec rails db:reset
  - bundle exec rspec
after_failure:
  - cat log/test.log
