language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3.4
  - 2.4.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake spec
addons:
  code_climate:
    repo_token: 16a5563f328e7241ec6257fd902ec4b0c0541faa26021e804d072a783cc05381
