language: ruby
cache: bundler
before_install:
  - gem install bundler 
rvm:
  - 2.2
  - 2.3.4
  - 2.4.1
  - 2.5.0
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: a74e9933c8093d8a99be5c3ba44b7a82554eec9505f4674356f305e4667144b1
