version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - /app/.git
      - /app/log
      - /app/node_modules
      - /app/tmp
      - /app/vendor
      - /app/db/sqlite
    ports:
      - "3000:3000"
