jobs:
  build:
    working_directory: ~/rails_twitter_clone
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          # https://discuss.circleci.com/t/how-to-add-a-path-to-path-in-circle-2-0/11554/4
          NPM_CONFIG_PREFIX: ~/.npm-global
      - image: circleci/mysql:5.7
        env:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%
    steps:
      - checkout

      - run:
          name: Install PhantomJS
          command: |
            npm install -g phantomjs-prebuilt
            sudo ln -sf /home/circleci/.npm-global/bin/phantomjs /usr/local/bin/phantomjs

      # Restore bundle cache
      - type: cache-restore
        key: rails-twitter-clone-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-twitter-clone-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rails db:create db:schema:load

      # RSpec
      - run: bundle exec rspec

      - store_artifacts:
          path: coverage
