version: 2.1

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test

commands:
  bundle_install:
    steps:
      # Restore bundle cache
      - restore_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install
      - sayhello
  rspec:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install

      # Database setup
      - run: bundle exec rails db:create db:schema:load
      # RSpec
      - run: bundle exec rspec

      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
  rubocop:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install

      # RuboCop
      - run: bundle exec rubocop

workflows:
  test:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
      - rubocop:
          requires:
            - setup
