jobs:
  build:
    working_directory: ~/rails_twitter_clone
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          # https://discuss.circleci.com/t/how-to-add-a-path-to-path-in-circle-2-0/11554/4
          BASH_ENV: ~/.bashrc
          NPM_CONFIG_PREFIX: ~/.npm-global
      - image: circleci/mysql:5.7
        env:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: npm install
          command: |
            npm install -g phantomjs-prebuilt
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # RSpec
      - run: bundle exec rspec

      - store_artifacts:
          path: coverage
