version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rails db:create db:schema:load

      # RSpec
      - run: bundle exec rspec
      
      # RuboCop
      - run: bundle exec rubocop

      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
