version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  node: circleci/node@4.2.0
  ruby: circleci/ruby@1.1.2

executors:
  default:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          RAILS_ENV: test

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt update
            sudo apt install libsqlite3-dev
      - ruby/install-deps:
          key: gems-v2
  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: bin/rails db:schema:load --trace
      - ruby/rspec-test
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2
      - ruby/rubocop-check

workflows:
  build:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
      - rubocop:
          requires:
            - setup
