version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

executors:
  default:
    working_directory: ~/app
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          RAILS_ENV: test

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run: brew install sqlite3
      - ruby/install-deps
  rspec:
    executor: default
    steps:
      - checkout
      - run: gem install bundler
      - ruby/install-deps
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
      - store_test_results:
          path: ~/test-results/rspec/
  rubocop:
    executor: default
    steps:
      - checkout
      - run: gem install bundler
      - ruby/install-deps
      - run: bundle exec rubocop

workflows:
  build:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
      - rubocop:
          requires:
            - setup
