jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RAILS_ENV: test
          PHANTOM_JS_VERSION: 2.1.1
    steps:
      - checkout

      - run:
          name: Install PhantomJS
          command: |
            mkdir -p ~/.phantomjs/${PHANTOM_JS_VERSION}
            curl -L --output ~/.phantomjs/${PHANTOM_JS_VERSION}/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOM_JS_VERSION}-linux-x86_64.tar.bz2
            tar xfvj ~/.phantomjs/${PHANTOM_JS_VERSION}/phantomjs.tar.bz2 -C ~/.phantomjs/${PHANTOM_JS_VERSION}/
            chmod ugo+x ~/.phantomjs/${PHANTOM_JS_VERSION}/phantomjs-${PHANTOM_JS_VERSION}-linux-x86_64/bin/phantomjs
            sudo ln -sf ~/.phantomjs/${PHANTOM_JS_VERSION}/phantomjs-${PHANTOM_JS_VERSION}-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs

      # Restore bundle cache
      - type: cache-restore
        key: rails-twitter-clone-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-twitter-clone-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rails db:create db:schema:load

      # RSpec
      - run: bundle exec rspec

      - store_artifacts:
          path: coverage
