version: 2.1

orbs:
  bundle-install: toshimaru/bundle-install@0.3.1

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run: gem install bundler
      - bundle-install/bundle-install
  rspec:
    executor: default
    steps:
      - checkout
      - run: gem install bundler
      - bundle-install/bundle-install
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
      - store_test_results:
          path: ~/test-results/rspec/
  rubocop:
    executor: default
    steps:
      - checkout
      - run: gem install bundler
      - bundle-install/bundle-install
      - run: bundle exec rubocop

workflows:
  build:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
      - rubocop:
          requires:
            - setup
