name: Coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: CodeClimate
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get remove google-chrome-stable
        sudo apt-get install libsqlite3-dev chromium-driver
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('**/Gemfile.lock')}}
        restore-keys: bundler-
    - name: bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: a74e9933c8093d8a99be5c3ba44b7a82554eec9505f4674356f305e4667144b1
      with:
        coverageCommand: bundle exec rspec
