name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    name: CodeClimate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install shared-mime-info
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Setup webpacker
      run: |
        yarn install
        bin/webpack
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: a74e9933c8093d8a99be5c3ba44b7a82554eec9505f4674356f305e4667144b1
      with:
        coverageCommand: bundle exec rspec
