name: Docker Compose Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build & Test
      run: |
        docker-compose build
        docker-compose run web rspec
