name: Docker Compose
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose build
    - run: docker-compose run web bundle exec rspec
