name: Docker Compose
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Build & Test
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose build
    - run: docker-compose run web rspec
