name: macOS
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
    runs-on: macos-latest
    name: RSpec
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Dependencies
      run: |
        brew update
        brew cask install google-chrome chromedriver
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-bundler-${{ hashFiles('**/Gemfile.lock')}}
        restore-keys: ${{ runner.os }}-${{ matrix.ruby }}-bundler-
    - name: bundle install
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: bundle exec rspec
