name: macOS
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x]
    runs-on: macos-latest
    name: RSpec
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    - name: Install Dependencies
      run: |
        brew update
        brew cask install google-chrome chromedriver
    - name: Run RSpec
      run: |
        bundle update --bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
