name: RuboCop
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: RuboCop
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev chromium-driver
    - name: bundle install
      run: |
        gem install bundler
        bundle update --bundler
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bundle exec rubocop -f html -o tmp/rubocop/report.html
