name: RuboCop
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: RuboCop
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: bundle install
      run: |
        gem install bundled_gem
        bgem install rubocop-rails_config
    - name: Run RuboCop
      run: rubocop -f progress -f html -o tmp/rubocop/report.html
    - uses: actions/upload-artifact@master
      with:
        name: rubocop-report
        path: tmp/rubocop/report.html
