name: Ubuntu
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ruby: [2.6.x]
    runs-on: ubuntu-latest
    name: RSpec
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    - name: Run RSpec
      run: |
        bundle update --bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
